name: Build APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    - name: Install Dependencies
      run: flutter pub get

    - name: Set up Android SDK
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
      run: |
        echo "Setting up Android SDK"
        setx ANDROID_HOME C:\Android
        setx PATH "%PATH%;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools"

    - name: Flutter Doctor
      run: flutter doctor

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
