name: Build APK (Dev)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the specified branch
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    # Install flutter
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    - name: Locate font_awesome_flutter and Run configurator.sh
      run: |
        flutter pub get
  
        # Locate package_config.json
        CONFIG_PATH=".dart_tool/package_config.json"
        if [ ! -f "$CONFIG_PATH" ]; then
          echo "Error: package_config.json not found."
          exit 1
        fi
  
        # Parse package_config.json to find font_awesome_flutter's rootUri
        ROOT_URI=$(jq -r '.packages[] | select(.name == "font_awesome_flutter") | .rootUri' $CONFIG_PATH)
  
        if [ "$ROOT_URI" == "" ]; then
          echo "Error: font_awesome_flutter not found in package_config.json."
          exit 1
        fi
  
        # Navigate to the dependency's util folder
        DEPENDENCY_DIR="$(echo $ROOT_URI | sed 's|file://||')"
        cd "$DEPENDENCY_DIR/"
        flutter pub get

        cd "$DEPENDENCY_DIR/util"
  
        # Run configurator.sh
        chmod +x configurator.sh
        ./configurator.sh
    # Step 5: Set up Android SDK (Version 34.0.0)
    - name: Set up Android SDK
      run: |
        sudo apt install -y wget unzip
        mkdir -p $ANDROID_HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8502546_latest.zip -O /tmp/cmdline-tools.zip
        unzip -q /tmp/cmdline-tools.zip -d $ANDROID_HOME
        mkdir -p $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34"
        
        echo "ANDROID_HOME set to $ANDROID_HOME"
      env:
        ANDROID_HOME: /home/runner/android-sdk      

    # Step 4: Install Flutter dependencies
    - name: Install Dependencies
      run: flutter pub get

    # Step 6: Run flutter doctor to validate setup
    - name: Flutter Doctor
      run: flutter doctor

    # Step 7: Build the APK
    - name: Build APK
      run: flutter build apk --release

    # Step 8: Upload APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-dev.apk
        path: build/app/outputs/flutter-apk/app-release-dev.apk
