name: Build APK

on:
  workflow_dispatch:


jobs:
  build-apk:
    runs-on: ubuntu-latest
    

    
    steps:

    - name: Show Current Working Directory
      run: | 
          pwd
        # Install flutter
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    # Step 1: Checkout the specified branch
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Show Current Working Directory
      run: | 
          pwd
          ls
    
    # Clone font_awesome_flutter and configure it    
    - name: Clone font_awesome_flutter and Run configurator.sh
      run: |
        git clone https://github.com/fluttercommunity/font_awesome_flutter.git
        flutter pub add ansicolor
        flutter pub add recase
        flutter pub add version
        cd font_awesome_flutter/util
        
        chmod +x configurator.sh
        ./configurator.sh --dynamic
        cd ..
        cd ..  
    - name: Show Current Working Directory (#2)
      run: | 
          pwd
          ls
          
     # Set up Android SDK (Version 34.0.0)
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
          
    # Step 4: Install Flutter dependencies
    - name: Install Dependencies
      run: flutter pub get

    # Step 6: Run flutter doctor to validate setup
    - name: Flutter Doctor
      run: flutter doctor

    # Step 7: Build the APK
    - name: Build APK
      run: flutter build apk --release

    - name: Create Release
      id: create_release
      uses: comnoco/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
            
    # Step 8: Upload APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-dev.apk
        path: build/app/outputs/flutter-apk/app-release.apk
