name: Build and Release Flutter App

on:
  workflow_dispatch:


jobs:
  build:
    name: Build Flutter Project
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Upload artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
          cp build/app/outputs/bundle/release/app-release.aab artifacts/

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get contributors and commits
        id: changelog
        run: |
          echo "# Changelog" > changelog.md
          echo "\n## Contributors and Commits" >> changelog.md
          git log --pretty=format:'- %an: %s' >> changelog.md

      - name: Create GitHub Release
        run: |
          echo "Creating GitHub release for tag $GITHUB_REF_NAME"
          echo "Release changelog:"
          cat changelog.md

      - name: Upload release assets
        run: |
          echo "Uploading APK and AAB to release artifacts"
          ls -l artifacts