name: Build and Release Flutter App

on:
  workflow_dispatch:


jobs:
  build:
    name: Build Flutter Project
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:3.24.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      # Clone font_awesome_flutter and configure it    
      - name: Clone font_awesome_flutter and Run configurator.sh
        run: |
          if [ -d "font_awesome_flutter" ]; then rm -rf font_awesome_flutter; fi
          
          
          git clone https://github.com/fluttercommunity/font_awesome_flutter.git
          flutter pub add ansicolor
          flutter pub add recase
          flutter pub add version
          cd font_awesome_flutter/util
          
          chmod +x configurator.sh
          ./configurator.sh --dynamic
          cd ..
          cd ..  

            
      - name: Install dependencies
        run: flutter pub get

      - name: Show Current Working Directory
        run: | 
          pwd
          ls

      - name: Remove Gradle Caches
        run: |
          rm -rf /root/.gradle/daemon
          rm -rf /root/.gradle/caches

      
      - name: Build APK
        run:  flutter build apk --release --verbose


      - name: Build AppBundle
        run: flutter build appbundle

      - name: Upload artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
          cp build/app/outputs/bundle/release/app-release.aab artifacts/
      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-release-apk
          path: artifacts/app-release.apk
  
      - name: Upload AAB to GitHub Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-release-aab
          path: artifacts/app-release.aab

  release:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:3.24.5
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

        

      - name: Download APK and AAB
        uses: actions/download-artifact@v3
        with:
          name: app-release-apk
          path: ./artifacts

      - name: Get contributors and commits
        id: changelog
        run: |
          echo "# Changelog" > changelog.md
          echo "\n## Contributors and Commits" >> changelog.md
          git log --pretty=format:'- %an: %s' >> changelog.md

      - name: Create GitHub Release
        run: |
          echo "Creating GitHub release for tag $GITHUB_REF_NAME"
          echo "Release changelog:"
          cat changelog.md

      - name: Upload APK to release assets
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-release.apk
          path: artifacts/app-release.apk

      - name: Upload AAB to release assets
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-release.aab
          path: artifacts/app-release.aab